# Generated by Django 5.1.13 on 2025-10-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("document", "Document"),
                            ("video", "Video"),
                            ("template", "Template"),
                            ("guide", "Guide"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("all", "All Users"),
                            ("student", "Student"),
                            ("mentor", "Mentor"),
                            ("supervisor", "Supervisor"),
                            ("admin", "Admin"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                ("file_url", models.URLField()),
                ("cover_image", models.URLField(blank=True, null=True)),
                ("download_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
