# Generated by Django 5.1.13 on 2025-10-23 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userprofile_controlled_interests_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupervisorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organisation", models.CharField(blank=True, max_length=255)),
                ("phone_number", models.CharField(blank=True, max_length=50)),
                ("wwcc_number", models.CharField(blank=True, max_length=100)),
                ("wwcc_expiry", models.DateField(blank=True, null=True)),
                ("wwcc_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervisor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Supervisor Profile",
                "verbose_name_plural": "Supervisor Profiles",
                "db_table": "supervisor_profiles",
            },
        ),
        migrations.CreateModel(
            name="StudentSupervisor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("supervisor", "Supervisor"),
                            ("guardian", "Guardian"),
                            ("mentor", "Mentor"),
                        ],
                        default="supervisor",
                        max_length=32,
                    ),
                ),
                ("join_permission_granted", models.BooleanField(default=False)),
                (
                    "join_permission_granted_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervisor_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervisee_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Supervisor Relationship",
                "verbose_name_plural": "Student Supervisor Relationships",
                "db_table": "student_supervisors",
                "indexes": [
                    models.Index(
                        fields=["student", "relationship_type"],
                        name="student_sup_student_5b8e1f_idx",
                    ),
                    models.Index(
                        fields=["supervisor"], name="student_sup_supervi_2643a1_idx"
                    ),
                ],
                "unique_together": {("student", "supervisor", "relationship_type")},
            },
        ),
    ]
